# Pandas 1

## Kameron Lightheart

## MATH 403 (Vol 3)

## 9/30/2019

In [0]:
import numpy as np
import pandas as pd
from google.colab import files

In [0]:
# Files needed
#     budget.csv
#     crime_data.csv
uploaded = files.upload()            

Saving budget.csv to budget.csv
Saving crime_data.csv to crime_data.csv


# Problem 1

In [0]:
def random_dataframe(d=None):
    """
    Generate a dictionary.
    Reset labels and return.

    Parameters:
    d (dict): dictionary to initialize DataFrame

    Return:
    csv: csv of DataFrame
    """
    result = None
    if d is not None:
        df = pd.DataFrame(d)
        index = df.index
        columns = df.columns
        values = df.values
        result = (index, columns, values)
    else:
        values = np.random.random((5,6))
        columns = ['A', 'B', 'C', 'D', 'E']
        index = ['I', 'II', 'III', 'IV', 'V', 'VI']
        df = pd.DataFrame(values, columns, index)
        result = (index, columns, values)
    return result

In [0]:
random_dataframe()

(['I', 'II', 'III', 'IV', 'V', 'VI'],
 ['A', 'B', 'C', 'D', 'E'],
 array([[0.76503407, 0.50363147, 0.20849664, 0.41652951, 0.24831311,
         0.29976917],
        [0.83382511, 0.82342529, 0.52257321, 0.09818262, 0.56870424,
         0.16237243],
        [0.84007801, 0.85796126, 0.34535862, 0.74494947, 0.05758676,
         0.14283527],
        [0.0576391 , 0.3113095 , 0.21799263, 0.01489144, 0.27569932,
         0.94312121],
        [0.00302279, 0.36673208, 0.94097693, 0.86973856, 0.98727686,
         0.29790359]]))

In [0]:

values = np.random.random((5,6))
columns = ['A', 'B', 'C', 'D', 'E']
index = ['I', 'II', 'III', 'IV', 'V', 'VI']
df = pd.DataFrame(values, columns, index)
random_dataframe(df)

(Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['I', 'II', 'III', 'IV', 'V', 'VI'], dtype='object'),
 array([[0.08152808, 0.5850206 , 0.9370239 , 0.6541566 , 0.80056373,
         0.76875558],
        [0.87511818, 0.99519632, 0.93920394, 0.37214999, 0.77523357,
         0.19600282],
        [0.53775708, 0.74185314, 0.05257287, 0.44152808, 0.82571473,
         0.96610458],
        [0.62115365, 0.23797084, 0.17665642, 0.41192467, 0.26968051,
         0.87458755],
        [0.62232405, 0.93713308, 0.75054039, 0.49839944, 0.53742758,
         0.02139768]]))

# Problem 2

In [0]:
# Prob 2
def prob2(file='budget.csv'):
    """
    Read in file as DataFrame. Manipulate data using
    Pandas commmands
    
    Parameters:
        file (str): name of datafile
        
    Return:
        values (ndarray): values of DataFrame
    """
    # Read in data
    df = pd.read_csv(file)
    
    # Get column names
    column_names = list(df)
    
    # Construct new order of column names
    order_indicies = [3, 4, 0, 1, 2, 5, 6, 7]
    new_order = [column_names[i] for i in order_indicies]
    
    # Reindex the DataFrame
    df = df.reindex(columns = new_order)
    
    # Sort on Groceries 
    df = df.sort_values('Groceries', ascending=False)
    
    # Reset all values in rent to 800
    df['Rent'] = 800 * np.ones_like(df['Rent']) 
    
    # Reset all values in first 5 rows to 0.0
    df[:5] = np.zeros_like(df.loc[28])
    
    return df.values

In [73]:
prob2()

array([[0, 0.0, 0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0, 0.0, 0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0, 0.0, 0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0, 0.0, 0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0, 0.0, 0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [174, 37.0, '11/18', 800.0, 90.0, 30.0, 23.0, 8.0],
       [174, 35.0, '4/15', 800.0, 82.0, nan, 26.0, nan],
       [172, 31.0, '8/18', 800.0, 82.0, 30.0, 26.0, 8.0],
       [171, 40.0, '5/15', 800.0, 82.0, nan, 23.0, nan],
       [171, 35.0, '7/15', 800.0, 82.0, nan, 27.0, nan],
       [171, 30.0, '6/17', 800.0, 80.0, 31.0, 22.0, nan],
       [170, 34.0, '10/18', 800.0, 90.0, 33.0, nan, 8.0],
       [170, 34.0, '7/16', 800.0, 85.0, nan, 25.0, nan],
       [167, 30.0, '3/16', 800.0, 92.0, nan, 29.0, nan],
       [163, 30.0, '5/16', 800.0, 85.0, nan, nan, nan],
       [163, 31.0, '1/15', 800.0, 90.0, nan, 25.0, nan],
       [161, 30.0, '6/16', 800.0, 85.0, nan, 24.0, nan],
       [160, 32.0, '12/16', 800.0, 91.0, 28.0, 23.0, nan],
       [158, nan, '1/16', 80

# Problem 3

In [0]:
def prob3(file='budget.csv'):
    """
    Read in data as Pandas DataFrame.
    Manipulate data and return DataFrame values.
    
    Parameters:
        file (str): data file
    
    Return:
        values (ndarray): values of DataFrame
    """
    # Read in data
    df = pd.read_csv(file)
    # Fill in nans with 0.0 
    df = df.fillna(0.0)
    df['Living Expenses'] = df['Rent'].values + df['Groceries'].values + df['Gas'].values\
                            + df['Utilities']
    df['Other'] = df['Dining Out'].values + df['Out With Friends'].values \
                            + df['Netflix']
    # Rent correlates most with living expenses, dining out for other
    corr = df.corr()
    
    means = df.mean()
    
    return (means['Rent'], means['Dining Out'])

In [242]:
prob3()

(751.0416666666666, 30.5)

# Problem 4

In [0]:
def prob4(file='crime_data.csv'):
    """
    Read in crime data and use SQL queries to gather certain data.
    
    Parameters:
        file (str): data
    
    Return:
        values (ndarray): values of DataFrame
    """
    df = pd.read_csv(file)
    df = df.set_index('Year')
    df['Rate'] = df['Total'].values / df['Population'].values
    df = df[df['Rate'] > 0.05]
    num_murders = df['Murder']
    return num_murders.values

In [226]:
prob4()

array([20510, 18780, 19120, 19560, 21460, 23040, 22520, 21010, 19310,
       18690, 18980, 20613, 20096, 20680, 21500, 23440, 24700, 23760,
       24530, 23330, 21610, 19650])

# Problem 5

In [0]:
def prob5(file = 'crime_data.csv'):
    """
    Read in crime data and use pandas to answer questions.
    
    Parameters:
        file (str): data
    
    Return:
        ans_1 (list): answer to Question 1
        ans_2 (ndarray): answer to Question 2
        ans_3 (float): answer to Question 3
    """
    # Read in the data
    df = pd.read_csv(file)
    # QUESTION 1
    # Compute the mean and correlation matrix
    means = df.mean(axis=0)
    # Three highest means are burlary, property and larceny
    means = means[means > 1_500_000]
    # Two most correlated are property and larceny
    correlations = df.corr()
    # Property has greatest max value
    ans1 = 'Property'
    
    # QUESTION 2
    recent_data = df[df['Year'] >= 2000]
    sorted_data = recent_data.sort_values('Murder')
    query_data = sorted_data[sorted_data['Aggravated Assault'] > 850_000]
    ans2 = query_data
    
    # QUESTION 3
    totals = df.groupby(df['Year'] // 10 * 10).sum().sort_values('Total', ascending=False).loc[1990]
    ans3 = float(totals['Property'] / totals['Total'])
    
    return [ans1, ans2, ans3]

In [204]:
prob5()

['Property',
     Year  Population     Total  ...  Burglary  Larceny  Vehicle Theft
 40  2000   281421906  11608072  ...   2050992  6971590        1160002
 41  2001   285317559  11876669  ...   2116531  7092267        1228391
 42  2002   287973924  11878954  ...   2151252  7057370        1246646
 43  2003   290690788  11826538  ...   2154834  7026802        1261226
 45  2005   296507061  11565499  ...   2155448  6783447        1235859
 47  2007   301621157  11251828  ...   2176140  6568572        1095769
 46  2006   299398484  11401511  ...   2183746  6607013        1192809
 
 [7 rows x 12 columns],
 0.8716622376104707]