In [1]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import train_test_split
from timeit import default_timer as time
import xgboost as xgb
from sklearn.neural_network import MLPClassifier as NeuralNetwork
from pomegranate import *

In [2]:
X = []
y = []
for i in range(36):
    data = np.load(r'C:\Users\Kameron Lightheart\Desktop\dataprojectvol3\window_files\BOX{}_topo.npy'.format(i))#.flatten()
    label = np.load(r'C:\Users\Kameron Lightheart\Desktop\dataprojectvol3\2020-03-28_19.52_16_5_10_100\BOX{}_ADJ.npy'.format(i))#.flatten()
    
    if data.shape[0] == data.shape[1]:
        # add the most likely box the lost person would end up in
        label = np.argmax(label, axis=1)
        
        for i in range(len(label)):
            # Add as a data point (x, y) the topology file along with the most 
            # likely box the lost person would end up in starting at each box
            X.append(data.flatten())
            y.append(label[i])

In [3]:
X = np.array(X)
y = np.array(y)
print(X.shape)
print(y.shape)
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print(x_train.shape, y_train.shape)

print(len(set(y)))

(3630, 25921)
(3630,)
(2541, 25921) (2541,)
121


# Bayesian Network

In [ ]:
# Note that we do not use the exact algorithm as it runs in exponential time
model = BayesianNetwork.from_samples(X)

In [39]:
model = RandomForestClassifier()
start = time()
model.fit(x_train, y_train)
end = time() - start
accuracy = model.score(x_test, y_test)

print("RandomForest Time: {}".format(end))
print("RandomForest Accuracy: {}".format(accuracy))

RandomForest Time: 47.918042800039984
RandomForest Accuracy: 0.004591368227731864


In [43]:
model = GradientBoostingClassifier()
start = time()
model.fit(x_train, y_train)
end = time() - start
accuracy = model.score(x_test, y_test)

print("GradientBoost Time: {}".format(end))
print("GradientBoost Accuracy: {}".format(accuracy))

KeyboardInterrupt: 

In [ ]:
dtrain = xgb.DMatrix(x_train, label=y_train)
dtest = xgb.DMatrix(x_test, label=y_test)
n_class = len(set(y_train))
param = {'max_depth':2, 'eta':1, 'objective':'multi:softmax', 'num_class':n_class}
num_round = 2
start = time()
bst = xgb.train(param, dtrain, num_round)
end = time() - start
pred = bst.predict(dtest)
num_correct = 0
for i in range(len(y_test)):
    if y_test[i] == pred[i]:
        num_correct += 1

print("XGBoost Accuracy: {}".format(num_correct / len(y_test)))
print("XGBoost Time: {}".format(end))

## Multi-Output Attempt Sklearn

In [66]:
multi_X = []
multi_y = []
for i in range(36):
    data = np.load(r'C:\Users\Kameron Lightheart\Desktop\dataprojectvol3\window_files\BOX{}_topo.npy'.format(i))#.flatten()
    label = np.load(r'C:\Users\Kameron Lightheart\Desktop\dataprojectvol3\2020-03-28_19.52_16_5_10_100\BOX{}_ADJ.npy'.format(i))#.flatten()
    
    if data.shape[0] == data.shape[1]:
        
        
        label = np.argmax(label, axis=1)
            
        multi_X.append(data.flatten())
        multi_y.append(label)
            
multi_X = np.array(multi_X)
multi_y = np.array(multi_y)

multi_x_train, multi_x_test, multi_y_train, multi_y_test = train_test_split(multi_X, multi_y, test_size=0.3)

In [67]:
print(multi_y_train)
print(multi_y.shape)
print(multi_x_train.shape)

[[  1   1   2 ... 118 120 120]
 [  0   1   3 ... 119 119 120]
 [  0   1   2 ... 119 119 120]
 ...
 [  0   2   4 ... 119 120 120]
 [  0   1   2 ... 119 120 120]
 [  0   2   2 ... 118 120 120]]
(30, 121)
(21, 25921)


In [68]:
multi_model = MultiOutputClassifier(RandomForestClassifier())
start = time()
multi_model.fit(multi_x_train, multi_y_train)
end = time() - start
accuracy = multi_model.score(multi_X, multi_y)

print("Multi RandomForest Time: {}".format(end))
print("Multi RandomForest Accuracy: {}".format(accuracy))

Multi RandomForest Time: 11.905005100008566
Multi RandomForest Accuracy: 0.7


In [1]:
from torchvision import models
fcn = models.segmentation.fcn_resnet101(pretrained=True).eval()

ModuleNotFoundError: No module named 'torchvision'

In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
import torch

img = Image.open(r'C:\Users\Kameron Lightheart\Downloads\google_image.jpeg')
plt.imshow(img); plt.show()